server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri: mongodb://root:123456@localhost:27017
      database: xc_cms
  rabbitmq:
    host: 192.168.56.101
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  xuecheng:
    mq:
      #cms客户端监控队列名称（不同的客户端监控的队列不能重复）
      queue: queue_cms_postpage_01
      routingKey: 5a751fab6abb5044e0d19ea1  #此routingKey为门户站点ID
  freemarker:
    cache: false
    settings:
      template_update_delay: 0